<?php
/**
 * @file
 * E-resource content type and Views for Ding!
 */

/**
 * Implements hook_init().
 */
function ding_eresource_init() {
  // Add our own stylesheet.
  drupal_add_css(drupal_get_path('module', 'ding_eresource') . '/css/ding_eresource.css');
}

/**
 * Implements hook_theme_registry_alter().
 */
function ding_eresource_theme_registry_alter(&$theme_registry) {
  // We provide our own node templates, so look here as well.
  $theme_path = drupal_get_path('module', 'ding_eresource') . '/templates';
  $theme_hooks = array('node');
  foreach ($theme_hooks as $hook) {
    $theme_registry[$hook]['theme paths'][] = $theme_path;
  }
}

/**
 * Implements hook_nodeapi().
 */
function ding_eresource_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // Set default breadcrumb if:
  // - viewing a e-resource node.
  // - on a page by itself.
  if (($node->type == 'eresource') &&
      ($op == 'view') && !$a3 && $a4) {
    $trail = array(
      l(t('Home'), '<front>'),
    );

    $trail[] = l(t('E-resurser'), 'e-resurser');

    drupal_set_breadcrumb($trail);
  }
}

/**
 * Implements hook_views_pre_view().
 */
function ding_eresource_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'eresource_list' && $display_id == 'panel_pane_1') {
    // Use an empty argument insteald of the wildcard value, so it
    // doesn't trigger title rewriting.
    if ($args[0] == 'alle') {
      $args[0] = NULL;
    }

    // Modify the second argument to be nothing if it's not a single letter.
    if (isset($args[1]) && !preg_match('/^\w$/', $args[1])) {
      dpm('hepss');
      $args[1] = NULL;
    }

    // Fix the path as the base path if neither argument has a value.
    $view->override_path = 'e-resurser' . implode('/', array_filter($args));
  }
}

/**
 * Preprocess variables for the node template.
 */
function ding_eresource_preprocess_node(&$vars) {
  // Link from the logo image to the resource.
  if (isset($vars['field_list_image'][0]) && isset($vars['field_link'][0]['url'])) {
    $vars['field_list_image'][0]['view'] = l(
      theme('imagecache', '120_120', $vars['field_list_image'][0]['filepath']),
      $vars['field_link'][0]['url'], array(
        'html' => TRUE,
        'attributes' => array(
          'title' => t('Go to !eresource_name', array('!eresource_name' => ($vars['field_link'][0]['title']) ? $vars['field_link'][0]['title'] : $vars['node']->title)),
        ),
      )
    );
  }
}

include_once 'ding_eresource.features.inc';
